### ISSUE TITLE
Add into F-Droid

### ISSUE THREAD

**Issue by KOLANICH** [cdeange/hubbub#1]

**Comment by christiandeange** [comment]
This app depends on Google Play Services for push notifications and therefore violates one of the F-Droid inclusion requirements:
> We cannot build apps using Google’s proprietary “play-services”. Please talk to upstream about an untainted build flavor (either using microg or removing non-free deps completely).

**Comment by KOLANICH** [comment]
There is a free substitute called [MicroG](https://microg.org/). It's already in F-Droid.

**Comment by christiandeange** [comment]
It's not worth investing the time for me to maintain a FLOSS fork of this library and yet another app store listing.

**Comment by KOLANICH** [comment]
It's not a library, it's dropin replacement having the same id. You just install it instead of gsf and apps use it as if it was real gsf (if the app doesn't check its signature).
